# Generated by Django 5.0 on 2025-06-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionwearaddons',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fashionwearaddons',
            name='category',
            field=models.CharField(choices=[('Topwear', 'Topwear'), ('Bottomwear', 'Bottomwear'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'), ('Ethnic', 'Ethnic Wear'), ('Sportswear', 'Sportswear'), ('Winterwear', 'Winterwear'), ('Innerwear', 'Innerwear'), ('Saree', 'Saree'), ('Kurti', 'Kurti')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashionwearaddons',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Multicolor', 'Multicolor'), ('Other', 'Other')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashionwearaddons',
            name='material',
            field=models.CharField(blank=True, choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Silk', 'Silk'), ('Linen', 'Linen'), ('Denim', 'Denim'), ('Wool', 'Wool'), ('Leather', 'Leather'), ('Blended', 'Blended'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fashionwearaddons',
            name='occasion',
            field=models.CharField(blank=True, help_text='E.g., Casual, Party, Formal, Festival', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fashionwearaddons',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex'), ('Kids', 'Kids'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fashionwearaddons',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2XL'), ('XXXL', '3XL'), ('Free Size', 'Free Size')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobiledevicesaccessories',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Realme', 'Realme'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Nokia', 'Nokia'), ('Motorola', 'Motorola'), ('Huawei', 'Huawei'), ('Honor', 'Honor'), ('Asus', 'Asus'), ('Lenovo', 'Lenovo'), ('Sony', 'Sony'), ('HTC', 'HTC'), ('Micromax', 'Micromax'), ('Infinix', 'Infinix'), ('Tecno', 'Tecno'), ('ZTE', 'ZTE'), ('Lava', 'Lava'), ('Gionee', 'Gionee'), ('Itel', 'Itel'), ('Panasonic', 'Panasonic'), ('Meizu', 'Meizu'), ('Google Pixel', 'Google Pixel'), ('BlackBerry', 'BlackBerry'), ('LeEco', 'LeEco'), ('Coolpad', 'Coolpad'), ('Sharp', 'Sharp'), ('Alcatel', 'Alcatel'), ('Blu', 'Blu'), ('Other', 'Other')], max_length=100),
        ),
    ]
