# Generated by Django 5.0 on 2025-06-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_fashionwearaddons_brand_fashionwearaddons_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcsperipherals',
            name='brand',
            field=models.CharField(choices=[('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('MSI', 'MSI'), ('Apple', 'Apple'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
