# Generated by Django 5.0 on 2025-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_pcsperipherals_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsappliances',
            name='appliance_type',
            field=models.CharField(blank=True, choices=[('kitchen', 'Kitchen Appliance'), ('home', 'Home Appliance'), ('personal', 'Personal Gadget'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
