# Generated by Django 5.0 on 2025-06-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_electronicsappliances_appliance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsappliances',
            name='brand',
            field=models.CharField(choices=[('cg', 'Chaudhary Group (CG)'), ('samsung', 'Samsung'), ('lg', 'LG'), ('sony', 'Sony'), ('panasonic', 'Panasonic'), ('philips', 'Philips'), ('whirlpool', 'Whirlpool'), ('bosch', 'Bosch'), ('lenovo', 'Lenovo'), ('dell', 'Dell'), ('other', 'Other')], default='Other', max_length=100),
        ),
    ]
