# Generated by Django 5.0 on 2025-06-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_electronicsappliances_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureappliances',
            name='brand',
            field=models.CharField(blank=True, choices=[('samsung', 'Samsung'), ('lg', 'LG'), ('whirlpool', 'Whirlpool'), ('bosch', 'Bosch'), ('ikea', 'IKEA'), ('godrej', 'Godrej'), ('local', 'Local Brand'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='furnitureappliances',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('grey', 'Grey'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('multi', 'Multicolor'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='furnitureappliances',
            name='material',
            field=models.CharField(blank=True, choices=[('wood', 'Wood'), ('metal', 'Metal'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('leather', 'Leather'), ('fabric', 'Fabric'), ('mixed', 'Mixed Materials'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='furnitureappliances',
            name='furniture_type',
            field=models.CharField(choices=[('sofa', 'Sofa'), ('bed', 'Bed'), ('table', 'Table'), ('chair', 'Chair'), ('wardrobe', 'Wardrobe'), ('shelf', 'Shelf'), ('appliance', 'Appliance'), ('other', 'Other')], max_length=100),
        ),
    ]
