# Generated by Django 5.0 on 2025-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_furnitureappliances_brand_furnitureappliances_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcsperipherals',
            name='pc_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Printer', 'Printer'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
