# Generated by Django 5.0 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_pcsperipherals_pc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmachinery',
            name='power_source',
            field=models.CharField(choices=[('electric', 'Electric'), ('gas', 'Gas'), ('manual', 'Manual'), ('battery', 'Battery Powered'), ('hydraulic', 'Hydraulic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='toolsmachinery',
            name='tool_type',
            field=models.CharField(choices=[('drill', 'Drill'), ('grinder', 'Grinder'), ('saw', 'Saw'), ('lathe', 'Lathe'), ('mixer', 'Mixer'), ('other', 'Other')], max_length=100),
        ),
    ]
