# Generated by Django 5.0 on 2025-06-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_toolsmachinery_power_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureappliances',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
