# Generated by Django 5.0 on 2025-06-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_furnitureappliances_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalinstruments',
            name='brand',
            field=models.CharField(blank=True, choices=[('yamaha', 'Yamaha'), ('roland', 'Roland'), ('fender', 'Fender'), ('gibson', 'Gibson'), ('korg', 'Korg'), ('casio', 'Casio'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='musicalinstruments',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicalinstruments',
            name='instrument_type',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('keyboard', 'Keyboard'), ('drums', 'Drums'), ('violin', 'Violin'), ('flute', 'Flute'), ('tabla', 'Tabla'), ('microphone', 'Microphone'), ('others', 'Others')], max_length=50),
        ),
    ]
