# Generated by Django 5.0 on 2025-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_musicalinstruments_brand_musicalinstruments_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthbeauty',
            name='product_type',
            field=models.CharField(choices=[('skincare', 'Skincare'), ('haircare', 'Haircare'), ('makeup', 'Makeup'), ('personal_care', 'Personal Care'), ('supplements', 'Supplements'), ('medical', 'Medical'), ('others', 'Others')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthbeauty',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthbeauty',
            name='brand',
            field=models.CharField(blank=True, choices=[('himalaya', 'Himalaya'), ('garnier', 'Garnier'), ('loreal', 'L’Oreal'), ('olay', 'Olay'), ('ponds', "Pond's"), ('dove', 'Dove'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthbeauty',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('sealed', 'Sealed'), ('used', 'Used')], default='new', max_length=20),
        ),
    ]
