# Generated by Django 5.0 on 2025-06-20 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('automobiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_automobiles', to='MainApp.automobiles')),
                ('books_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_books_education', to='MainApp.bookseducation')),
                ('cameras_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_cameras_accessories', to='MainApp.camerasaccessories')),
                ('electronics_appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_electronics_appliances', to='MainApp.electronicsappliances')),
                ('fashionwear_addons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_fashionwear_addons', to='MainApp.fashionwearaddons')),
                ('food_beverages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_food_beverages', to='MainApp.foodbeverages')),
                ('furniture_appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_furniture_appliances', to='MainApp.furnitureappliances')),
                ('health_beauty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_health_beauty', to='MainApp.healthbeauty')),
                ('household_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_household_accessories', to='MainApp.householdaccessories')),
                ('mobile_devices_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_mobile_devices_accessories', to='MainApp.mobiledevicesaccessories')),
                ('musical_instruments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_musical_instruments', to='MainApp.musicalinstruments')),
                ('pcs_peripherals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_pcs_peripherals', to='MainApp.pcsperipherals')),
                ('realestate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_realestate', to='MainApp.realestate')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to=settings.AUTH_USER_MODEL)),
                ('tools_machinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_tools_machinery', to='MainApp.toolsmachinery')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_avatar', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automobiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_automobiles', to='MainApp.automobiles')),
                ('books_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_books_education', to='MainApp.bookseducation')),
                ('cameras_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_cameras_accessories', to='MainApp.camerasaccessories')),
                ('electronics_appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_electronics_appliances', to='MainApp.electronicsappliances')),
                ('fashionwear_addons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_fashionwear_addons', to='MainApp.fashionwearaddons')),
                ('food_beverages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_food_beverages', to='MainApp.foodbeverages')),
                ('furniture_appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_furniture_appliances', to='MainApp.furnitureappliances')),
                ('health_beauty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_health_beauty', to='MainApp.healthbeauty')),
                ('household_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_household_accessories', to='MainApp.householdaccessories')),
                ('mobile_devices_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_mobile_devices_accessories', to='MainApp.mobiledevicesaccessories')),
                ('musical_instruments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_musical_instruments', to='MainApp.musicalinstruments')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='RatingReviews.comment')),
                ('pcs_peripherals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_pcs_peripherals', to='MainApp.pcsperipherals')),
                ('realestate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_realestate', to='MainApp.realestate')),
                ('tools_machinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_tools_machinery', to='MainApp.toolsmachinery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
